name: test01
description: "Pokemonアプリ（クリーンアーキテクチャ構成）"
publish_to: 'none'  # 公開しない場合はそのまま

version: 1.0.0+1    # アプリのバージョン+ビルド番号

environment:
  sdk: ^3.8.1       # 使用する Dart SDK バージョン

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0          # HTTPクライアント（Data層で使用）
  cupertino_icons: ^1.0.8  # iOS向けアイコン
  google_fonts: ^6.1.0     # Google Fontsを簡単に適用
  path_provider: ^2.1.4     # iOSのファイルパス取得（google_fontsのキャッシュ用に必要）

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0   # 推奨Lintルール
  flutter_launcher_icons: ^0.13.1  # アイコン自動生成

flutter:
  uses-material-design: true  # Material Icons を使用

# flutter_launcher_icons 設定（1枚の画像から各OS用アイコンを生成）
flutter_launcher_icons:
  image_path: assets/icon/app_icon.png
  android: true
  ios: true
  web:
    generate: true
    image_path: assets/icon/app_icon.png
    background_color: "#ffffff"
    theme_color: "#ffffff"
  macos:
    generate: true
    image_path: assets/icon/app_icon.png
  windows:
    generate: true
    image_path: assets/icon/app_icon.png
  linux:
    generate: true
    image_path: assets/icon/app_icon.png
